import {
  DENIED_PACKAGES,
  DEV_EXCEPTIONS,
  FORBIDDEN_PREFIXES,
  PERMISSIVE,
  type PackageLicense,
} from "./policy.ts";

export interface Closures {
  /** Production dependencies of the service, i.e. what the container image runs. */
  readonly service: readonly PackageLicense[];
  /** Production dependencies of every workspace package, tools included. */
  readonly production: readonly PackageLicense[];
  /** Every installed package, development tooling included. */
  readonly everything: readonly PackageLicense[];
}

/** Artifacts that reach users or CI without passing through the package manager. */
const ARTIFACTS: readonly { name: string; license: string; where: string }[] = [
  {
    name: "sentence-transformers/all-MiniLM-L6-v2 (ONNX weights and tokenizer)",
    license: "Apache-2.0",
    where: "service image; pinned revision and hashes in packages/search/models/all-minilm-l6-v2.json",
  },
  {
    name: "node:24 trixie-slim base image",
    license: "MIT (Node.js); Debian packages under their own free licences",
    where: "service image",
  },
  {
    name: "rs-soroban-env simple_account.wasm",
    license: "Apache-2.0",
    where: "tests only; packages/testkit/fixtures/README.md",
  },
  { name: "postgres:18 image", license: "PostgreSQL", where: "docker-compose and CI only" },
  { name: "stellar/quickstart image", license: "Apache-2.0", where: "docker-compose and CI only" },
];

const key = (pkg: PackageLicense) => `${pkg.name}@${pkg.version}`;

function sorted(packages: readonly PackageLicense[]): PackageLicense[] {
  const unique = new Map(packages.map((pkg) => [key(pkg), pkg]));
  return [...unique.values()].sort((a, b) => key(a).localeCompare(key(b)));
}

function counts(packages: readonly PackageLicense[]): string[] {
  const byLicense = new Map<string, number>();
  for (const pkg of packages) byLicense.set(pkg.license, (byLicense.get(pkg.license) ?? 0) + 1);
  return [...byLicense]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([license, count]) => `| ${license} | ${String(count)} |`);
}

/**
 * The dependency licence report, as Markdown. Deterministic for a given lockfile, so CI can check
 * that the committed report matches the installed tree.
 */
export function renderReport(closures: Closures): string {
  const service = sorted(closures.service);
  const serviceKeys = new Set(service.map(key));
  const production = sorted(closures.production);
  const productionKeys = new Set(production.map(key));
  const toolsOnly = production.filter((pkg) => !serviceKeys.has(key(pkg)));
  const development = sorted(closures.everything).filter((pkg) => !productionKeys.has(key(pkg)));
  const compound = sorted(closures.everything).filter((pkg) => /\s(OR|AND)\s/i.test(pkg.license));
  const exceptions = DEV_EXCEPTIONS.filter((exception) =>
    development.some((pkg) => pkg.name === exception.name && pkg.license === exception.license),
  );

  // YAML front matter titles the page on the documentation site; a YAML comment carries the notice,
  // because the site parses Markdown as MDX, where HTML comments are a syntax error.
  const lines = [
    "---",
    "# Generated by `pnpm license:report` from the lockfile. Do not edit; CI checks it is current.",
    "title: Dependency licences",
    "description: The licence of every dependency, and the policy the licence gate enforces.",
    "---",
    "",
    "Rail402 is Apache-2.0. Every package that runs in the service is under a permissive licence, and",
    "no copyleft licence appears anywhere in the tree, development tooling included, except the",
    "exceptions flagged below. The policy is enforced on every CI run by `pnpm license:gate`",
    "(`tools/license-gate/src/policy.ts`).",
    "",
    `- Permissive allowlist: ${[...PERMISSIVE].join(", ")}.`,
    `- Forbidden anywhere: ${FORBIDDEN_PREFIXES.map((prefix) => `${prefix}*`).join(", ")}.`,
    "- The OpenZeppelin Relayer, its x402 plugin and the relayer SDK are AGPL and are not used.",
    "",
    "## Summary",
    "",
    "| Closure | Packages |",
    "| --- | --- |",
    `| Service (the container image) | ${String(service.length)} |`,
    `| Other workspace tools (conformance runs, evaluation) | ${String(toolsOnly.length)} |`,
    `| Development only (build, lint, test) | ${String(development.length)} |`,
    "",
    "## Flagged items",
    "",
    "Refused whatever licence they declare:",
    "",
    "| Package | Reason | Present |",
    "| --- | --- | --- |",
    ...[...DENIED_PACKAGES].map(
      ([name, reason]) =>
        `| ${name} | ${reason} | ${closures.everything.some((pkg) => pkg.name === name) ? "**yes**" : "no"} |`,
    ),
    "",
    "Tolerated in development tooling only; never shipped:",
    "",
    "| Package | Licence | Reason |",
    "| --- | --- | --- |",
    ...(exceptions.length === 0
      ? ["| — | — | none installed |"]
      : exceptions.map((e) => `| ${e.name} | ${e.license} | ${e.reason} |`)),
    "",
    "Dual or compound licences (a permissive branch is always available):",
    "",
    "| Package | Licence |",
    "| --- | --- |",
    ...(compound.length === 0 ? ["| — | none |"] : compound.map((pkg) => `| ${key(pkg)} | ${pkg.license} |`)),
    "",
    "## Artifacts outside the package manager",
    "",
    "| Artifact | Licence | Where |",
    "| --- | --- | --- |",
    ...ARTIFACTS.map((artifact) => `| ${artifact.name} | ${artifact.license} | ${artifact.where} |`),
    "",
    "## Service packages",
    "",
    "| Package | Version | Licence |",
    "| --- | --- | --- |",
    ...service.map((pkg) => `| ${pkg.name} | ${pkg.version} | ${pkg.license} |`),
    "",
    "## Other workspace tools, by licence",
    "",
    "| Licence | Packages |",
    "| --- | --- |",
    ...counts(toolsOnly),
    "",
    "## Development only, by licence",
    "",
    "| Licence | Packages |",
    "| --- | --- |",
    ...counts(development),
    "",
  ];
  return lines.join("\n");
}
