#!/usr/bin/env node
/**
 * Fail-closed license gate over the FULL transitive dependency tree.
 *
 * Policy source of truth: license-policy.json .
 * Tooling: `pnpm licenses list --json` — built into pnpm >= 10.30, so the gate itself adds no
 * dependency to the tree it is auditing. (A license scanner that ships its own transitive tree is
 * a slightly silly thing to audit licenses with.)
 *
 * Exit codes:
 *   0  every package resolved to an allowed license (or an acknowledged review-class one)
 *   1  at least one blocked / unknown / unacknowledged-review package  -> build stops
 *   2  the gate could not run (missing lockfile, pnpm failure) -> also stops the build, by design
 *
 * Usage:
 *   node scripts/license-gate.mjs            # gate (CI)
 *   node scripts/license-gate.mjs --report   # gate + regenerate docs/licenses.md
 *   node scripts/license-gate.mjs --json     # machine-readable verdicts on stdout
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { VERDICT, classify } from "./lib/license-classify.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const POLICY_PATH = resolve(ROOT, "license-policy.json");
const REPORT_PATH = resolve(ROOT, "docs/licenses.md");

const argv = new Set(process.argv.slice(2));
const WANT_REPORT = argv.has("--report");
const WANT_JSON = argv.has("--json");

function fail(code, msg) {
  console.error(`\n  license-gate: ${msg}\n`);
  process.exit(code);
}

function loadPolicy() {
  let policy;
  try {
    policy = JSON.parse(readFileSync(POLICY_PATH, "utf8"));
  } catch (err) {
    fail(2, `cannot read license-policy.json: ${err.message}`);
  }
  for (const key of ["allow", "review", "block", "reviewPrefixes", "blockPrefixes"]) {
    if (!Array.isArray(policy[key])) fail(2, `license-policy.json: "${key}" must be an array`);
  }
  if (policy.acknowledged && typeof policy.acknowledged !== "object") {
    fail(2, `license-policy.json: "acknowledged" must be an object`);
  }
  return policy;
}

/**
 * Collect installed packages via pnpm. Returns [{ name, version, license, homepage }].
 * pnpm's JSON shape has drifted between minors, so accept both the
 * `{ "<license>": [ {name, versions|version, ...} ] }` map and a flat array.
 */
function collectPackages() {
  let raw;
  try {
    raw = execFileSync("pnpm", ["licenses", "list", "--json", "--recursive"], {
      cwd: ROOT,
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (err) {
    const stderr = (err.stderr || "").toString();
    // No dependencies installed yet is a legitimate state for a fresh scaffold: an empty tree
    // trivially satisfies the policy. Anything else is a real failure and must stop the build.
    if (/No packages found|no projects matched|Nothing to list/i.test(stderr + (err.stdout || ""))) {
      return [];
    }
    fail(2, `\`pnpm licenses list\` failed (is the lockfile present and node_modules installed?)\n${stderr.trim()}`);
  }

  const trimmed = raw.trim();
  if (!trimmed) return [];

  let parsed;
  try {
    parsed = JSON.parse(trimmed);
  } catch (err) {
    fail(2, `could not parse pnpm output as JSON: ${err.message}`);
  }

  const out = [];
  const push = (license, entry) => {
    const versions = entry.versions ?? (entry.version ? [entry.version] : ["*"]);
    for (const version of versions) {
      out.push({
        name: entry.name ?? "<unnamed>",
        version: String(version),
        license: (license ?? entry.license ?? "UNKNOWN").trim() || "UNKNOWN",
        homepage: entry.homepage ?? entry.repository ?? "",
      });
    }
  };

  if (Array.isArray(parsed)) {
    for (const entry of parsed) push(entry.license, entry);
  } else {
    for (const [license, entries] of Object.entries(parsed)) {
      for (const entry of entries ?? []) push(license, entry);
    }
  }
  return out;
}

function writeReport(rows) {
  const byVerdict = v => rows.filter(r => r.verdict === v);
  const table = list =>
    list.length === 0
      ? "_none_\n"
      : ["| Package | Version | License | Note |", "| --- | --- | --- | --- |"]
          .concat(list.map(r => `| \`${r.name}\` | ${r.version} | ${r.license} | ${r.detail || ""} |`))
          .join("\n") + "\n";

  const counts = Object.keys(VERDICT)
    .map(v => `${v}: ${byVerdict(v).length}`)
    .join(" · ");

  const body = `# Third-party license verdicts

<!-- GENERATED by scripts/license-gate.mjs — do not edit by hand. Run \`pnpm license:report\`. -->

Policy: [\`license-policy.json\`](../license-policy.json).
Scope: **full transitive tree**, all workspace projects.

**Generated:** ${new Date().toISOString()}
**Totals:** ${rows.length} package-versions — ${counts}

## Blocked (build fails)

${table(byVerdict("BLOCKED"))}
## Unknown (build fails — fail-closed)

${table(byVerdict("UNKNOWN"))}
## Needs human review (build fails until acknowledged)

${table(byVerdict("REVIEW"))}
## Acknowledged review-class exceptions

${table(byVerdict("ACKNOWLEDGED"))}
## Allowed

${table(byVerdict("ALLOWED"))}`;

  mkdirSync(dirname(REPORT_PATH), { recursive: true });
  writeFileSync(REPORT_PATH, body);
}

// ---------------------------------------------------------------------------

const policy = loadPolicy();
const packages = collectPackages();

// Deduplicate: the same package-version can appear under several workspace projects.
const seen = new Map();
for (const pkg of packages) {
  const key = `${pkg.name}@${pkg.version}`;
  if (!seen.has(key)) seen.set(key, pkg);
}

const rows = [...seen.values()]
  .map(pkg => ({ ...pkg, ...classify(pkg, policy) }))
  .sort((a, b) => VERDICT[a.verdict] - VERDICT[b.verdict] || a.name.localeCompare(b.name));

if (WANT_JSON) {
  console.log(JSON.stringify(rows, null, 2));
}

if (WANT_REPORT) {
  writeReport(rows);
  console.log(`license-gate: wrote ${REPORT_PATH.replace(ROOT + "/", "")}`);
}

const failing = rows.filter(r => r.verdict === "BLOCKED" || r.verdict === "UNKNOWN" || r.verdict === "REVIEW");

if (!WANT_JSON) {
  const counts = Object.keys(VERDICT).map(v => `${v}=${rows.filter(r => r.verdict === v).length}`);
  console.log(`license-gate: scanned ${rows.length} package-versions (${counts.join(" ")})`);
}

if (failing.length > 0) {
  console.error("\nlicense-gate: FAILED — the following packages are not permitted:\n");
  for (const r of failing) {
    console.error(`  [${r.verdict.padEnd(7)}] ${r.name}@${r.version} — ${r.license}${r.detail ? ` (${r.detail})` : ""}`);
  }
  console.error(
    [
      "",
      "How to resolve:",
      "  BLOCKED  — remove the dependency. Strong copyleft is a hard prohibition;",
      "             it can never be acknowledged, and AGPL in particular is fatal because we operate",
      "             this code as a network service.",
      "  UNKNOWN  — identify the real license and add it to license-policy.json, or remove the dep.",
      "  REVIEW   — a human decides, then records it under \"acknowledged\" with a reason.",
      "",
    ].join("\n"),
  );
  process.exit(1);
}

if (!WANT_JSON) console.log("license-gate: PASS — all dependencies permitted.\n");
